import React from "react";
import type { Metadata } from "next";
import Navbar from "@/components/layout/Navbar";
import TopBar from "@/components/layout/TopBar";
import Footer from "@/components/layout/Footer";
import WhatsAppButton from "@/components/shared/WhatsAppButton";
import SignInModalHandler from "@/components/modals/SignInModalHandler";
import NewsletterPopup from "@/components/modals/NewsletterPopup";

export const metadata: Metadata = {
  title: "First Step",
  description: "Generated by create next app",
};

export default async function WebsiteLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <React.Fragment>
      <div className="fixed top-0 left-0 right-0 z-50 w-full flex flex-col">
        <TopBar />
        <Navbar />
      </div>
      {/* Spacer for fixed header */}
      <div className="h-[135px] xl:h-[160px] w-full" aria-hidden="true" />
      {children}
      <WhatsAppButton />
      <Footer />
      <SignInModalHandler />
      <NewsletterPopup />
    </React.Fragment>
  );
}
