# -------- Base image --------
    FROM node:18-slim AS base

    ENV NEXT_TELEMETRY_DISABLED 1
    
    # Create app directory
    WORKDIR /app
    
    # -------- Dependencies --------
    FROM base AS deps
    
    # Install system dependencies required by Sharp
    RUN apt-get update && apt-get install -y \
        python3 make g++ \
        libcairo2-dev libjpeg-dev libpango1.0-dev libgif-dev librsvg2-dev \
        && rm -rf /var/lib/apt/lists/*
    
    # Copy package files and install dependencies
    COPY package*.json ./
    RUN npm ci --legacy-peer-deps
    
    # -------- Build --------
    FROM base AS builder
    
    # Copy deps
    COPY --from=deps /app/node_modules ./node_modules
    
    # Copy rest of app
    COPY . .
    
    # Safety: Clean any leftover build output first!
    RUN rm -rf .next
    
    # Build Next.js app
    RUN npm run build --force
    
    # Safety: Fail if standalone server.js is missing
    RUN test -f .next/standalone/server.js || (echo "❌ ERROR: server.js was NOT generated by Next.js build! Check your build logs." && exit 1)
    
    # -------- Runner --------
    FROM base AS runner
    
    # Add a non-root user
    RUN addgroup --system --gid 1001 nodejs && \
        adduser --system --uid 1001 nextjs
    
    WORKDIR /app
    
    # Copy built output
    COPY --from=builder /app/public ./public
    COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
    COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
    
    # Optional: if your runtime needs config files
    COPY --from=builder /app/next.config.ts ./
    
    # Use non-root user
    USER nextjs
    
    # Expose and run
    EXPOSE 3000
    ENV PORT=3000
    ENV HOSTNAME=0.0.0.0
    
    CMD ["node", "server.js"]
    